<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Create the `detection_events` table.
 *
 * Stores ONLY confirmed detection events reported by ESP32 devices.
 * Raw sensor readings are NEVER stored here.
 *
 * ARCHITECTURE REMINDER:
 * The ESP32 makes ALL detection decisions (tremor classification, FOG state machine).
 * Laravel is a passive recipient: it receives, stores, and displays confirmed events.
 * Laravel does NOT re-analyse or re-classify events.
 *
 * DESIGN NOTES:
 * - event_uuid ensures idempotent event ingestion.
 *   If the ESP32 retries an HTTP POST due to a network timeout, Laravel can detect
 *   the duplicate by checking event_uuid before inserting. No duplicate events are stored.
 *
 * - tremor_level is only meaningful for EventType::Tremor events. It is NULL for FOG events.
 *   Stored as tinyint (0–3) and cast to TremorLevel enum in the model.
 *
 * - device_detected_at = timestamp from ESP32 (NTP-synchronized).
 * - server_received_at = timestamp when Laravel API processed the POST.
 *   The difference reveals network latency and ESP32 clock drift over time.
 *
 * - cueing_activated = whether the ESP32 activated the vibration motor for this event.
 *   Relevant for FOG events. For tremor events, cueing is not used.
 *
 * - metadata is a generic JSON column. It deliberately has no fixed schema.
 *   Future firmware versions may include RMS values, motion scores, calibration
 *   version, confidence indicators, or other diagnostic fields without any
 *   database schema changes being required.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('detection_events', function (Blueprint $table) {
            $table->id();

            $table->uuid('event_uuid')
                  ->unique()
                  ->comment('UUID generated by ESP32 or assigned on first receipt; used for deduplication on retry');

            $table->foreignId('patient_id')
                  ->constrained('patients')
                  ->cascadeOnDelete();

            $table->foreignId('device_id')
                  ->constrained('devices')
                  ->cascadeOnDelete();

            $table->string('event_type', 20)
                  ->comment('tremor | fog (App\\Enums\\EventType). Set exclusively by ESP32 firmware.');

            $table->tinyInteger('tremor_level')
                  ->unsigned()
                  ->nullable()
                  ->comment('0=None,1=Mild,2=Moderate,3=Severe (App\\Enums\\TremorLevel). NULL for FOG events.');

            $table->timestamp('device_detected_at')
                  ->useCurrent()
                  ->comment('When the ESP32 confirmed the event (NTP-synchronized device clock)');

            $table->timestamp('server_received_at')
                  ->useCurrent()
                  ->comment('When this Laravel server received and processed the event report');

            $table->boolean('cueing_activated')
                  ->default(false)
                  ->comment('True if the ESP32 activated vibration cueing in response to this event');

            $table->timestamp('cueing_stopped_at')
                  ->nullable()
                  ->comment('When cueing was stopped — by automatic FOG recovery or a remote stop command');

            $table->json('metadata')
                  ->nullable()
                  ->comment('Generic extensible JSON: RMS values, motion score, firmware version, calibration data, etc.');

            $table->timestamps();

            // Composite indexes optimised for expected dashboard query patterns
            $table->index('event_type');
            $table->index('device_detected_at');
            $table->index(['patient_id', 'event_type'],        'de_patient_type_idx');
            $table->index(['patient_id', 'device_detected_at'],'de_patient_time_idx');
            $table->index(['device_id',  'device_detected_at'],'de_device_time_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('detection_events');
    }
};
